# Generated by Django 5.1.1 on 2026-08-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0002_nas_mac_address'),
        ('tenants', '0005_tenant_status_changed_at_tenant_status_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('cpu_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('memory_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disk_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('router_memory_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_samples', to='routers.nas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_samples', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('activity_date', models.DateField()),
                ('minutes_online', models.PositiveIntegerField(default=0)),
                ('upload_bytes', models.BigIntegerField(default=0)),
                ('download_bytes', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_activity', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'mac_address', 'activity_date')},
            },
        ),
    ]
