# Generated by Django 5.1.1 on 2026-08-20 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenant_status_changed_at_tenant_status_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurstProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate_limit', models.CharField(max_length=64)),
                ('burst_limit', models.CharField(blank=True, default='', max_length=64)),
                ('burst_threshold', models.CharField(blank=True, default='', max_length=64)),
                ('burst_time', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burst_profiles', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='FUPProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quota_gb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('throttled_rate', models.CharField(max_length=64)),
                ('reset_period', models.CharField(default='monthly', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fup_profiles', to='tenants.tenant')),
            ],
        ),
    ]
