# Generated by Django 5.0.3 on 2026-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nasname', models.CharField(max_length=128)),
                ('shortname', models.CharField(blank=True, max_length=32, null=True)),
                ('type', models.CharField(default='other', max_length=30)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.CharField(max_length=60)),
                ('server', models.CharField(blank=True, max_length=64, null=True)),
                ('community', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(default='RADIUS Client', max_length=200)),
            ],
            options={
                'db_table': 'nas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('acctsessionid', models.CharField(default='', max_length=64)),
                ('acctuniqueid', models.CharField(default='', max_length=32, unique=True)),
                ('username', models.CharField(default='', max_length=64)),
                ('realm', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('nasipaddress', models.GenericIPAddressField(default='')),
                ('nasportid', models.CharField(blank=True, max_length=32, null=True)),
                ('nasporttype', models.CharField(blank=True, max_length=32, null=True)),
                ('acctstarttime', models.DateTimeField(blank=True, null=True)),
                ('acctupdatetime', models.DateTimeField(blank=True, null=True)),
                ('acctstoptime', models.DateTimeField(blank=True, null=True)),
                ('acctinterval', models.IntegerField(blank=True, null=True)),
                ('acctsessiontime', models.PositiveIntegerField(blank=True, null=True)),
                ('acctauthentic', models.CharField(blank=True, max_length=32, null=True)),
                ('connectinfo_start', models.CharField(blank=True, max_length=120, null=True)),
                ('connectinfo_stop', models.CharField(blank=True, max_length=120, null=True)),
                ('acctinputoctets', models.BigIntegerField(blank=True, null=True)),
                ('acctoutputoctets', models.BigIntegerField(blank=True, null=True)),
                ('calledstationid', models.CharField(default='', max_length=50)),
                ('callingstationid', models.CharField(default='', max_length=50)),
                ('acctterminatecause', models.CharField(default='', max_length=32)),
                ('servicetype', models.CharField(blank=True, max_length=32, null=True)),
                ('framedprotocol', models.CharField(blank=True, max_length=32, null=True)),
                ('framedipaddress', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6address', models.GenericIPAddressField(blank=True, null=True)),
                ('framedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('framedinterfaceid', models.CharField(blank=True, max_length=44, null=True)),
                ('delegatedipv6prefix', models.GenericIPAddressField(blank=True, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=64, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default='==', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=64)),
                ('attribute', models.CharField(default='', max_length=64)),
                ('op', models.CharField(default='=', max_length=2)),
                ('value', models.CharField(default='', max_length=253)),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
    ]
