# Generated by Django 5.0.3 on 2026-08-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(help_text='IP or Domain of the NAS', max_length=128)),
                ('shortname', models.CharField(max_length=32)),
                ('secret', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('mikrotik', 'MikroTik'), ('coovachilli', 'CoovaChilli')], default='mikrotik', max_length=30)),
                ('is_online', models.BooleanField(default=False)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Network Access Server',
                'verbose_name_plural': 'Network Access Servers',
            },
        ),
    ]
